In [1]:
#load libraries 
import pandas as pd

In [6]:
data={
    'region' : ['kerala','karnataka','kerala','tamilnadu','assam'],
    'patient_age' : [34,56,48,47,39],
    'hypertension_status':[0,1,1,0,1],
    'bmi':[21.7,29.5,33.4,24.5,25]
}

In [7]:
df=pd.DataFrame(data)

In [8]:
print(df)

      region  patient_age  hypertension_status   bmi
0     kerala           34                    0  21.7
1  karnataka           56                    1  29.5
2     kerala           48                    1  33.4
3  tamilnadu           47                    0  24.5
4      assam           39                    1  25.0

In [9]:
df.head(2)

      region  patient_age  hypertension_status   bmi
0     kerala           34                    0  21.7
1  karnataka           56                    1  29.5

In [10]:
df.tail(3)

      region  patient_age  hypertension_status   bmi
2     kerala           48                    1  33.4
3  tamilnadu           47                    0  24.5
4      assam           39                    1  25.0

In [11]:
df.columns

Index(['region', 'patient_age', 'hypertension_status', 'bmi'], dtype='str')

In [12]:
df.isna()

   region  patient_age  hypertension_status    bmi
0   False        False                False  False
1   False        False                False  False
2   False        False                False  False
3   False        False                False  False
4   False        False                False  False

In [16]:
df.isna().sum().sum()

np.int64(0)

In [17]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   region               5 non-null      str
 1   patient_age          5 non-null      int64
 2   hypertension_status  5 non-null      int64
 3   bmi                  5 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 292.0 bytes
None

In [ ]:
# filter a separate df for patients who have high hypertension status=1
high_hypertension = df[df["hypertension_status"]==1]
high_hypertension

      region  patient_age  hypertension_status   bmi
1  karnataka           56                    1  29.5
2     kerala           48                    1  33.4
4      assam           39                    1  25.0

In [24]:
#mean of column oof high hypertension
bmi_mean = high_hypertension['bmi'].mean()
print(f"the average of bmi of high hypertension people are :{bmi_mean}")

the average of bmi of high hypertension people are :29.3

In [28]:
#grouping by region
region_count=df.groupby("region")["patient_age"].count()
region_count

region
assam        1
karnataka    1
kerala       2
tamilnadu    1
Name: patient_age, dtype: int64