In [17]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
lifestyle_data={
    'patient_id':[601,602,603,604],
    'city':["Udupi","Manipal","Udupi","Mangalore"],
    'smoker':["Yes","No","No","Yes"]
}

In [19]:
df=pd.DataFrame(lifestyle_data)

In [20]:
df

   patient_id       city smoker
0         601      Udupi    Yes
1         602    Manipal     No
2         603      Udupi     No
3         604  Mangalore    Yes

In [21]:
df.describe()

       patient_id
count    4.000000
mean   602.500000
std      1.290994
min    601.000000
25%    601.750000
50%    602.500000
75%    603.250000
max    604.000000

In [22]:
df.isna().sum()

patient_id    0
city          0
smoker        0
dtype: int64

In [23]:
df.columns

Index(['patient_id', 'city', 'smoker'], dtype='str')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  4 non-null      int64
 1   city        4 non-null      str
 2   smoker      4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [26]:
# one hot encoding
#convert smoker column into binary indicator columns

df_encoded = pd.get_dummies(df,columns=["smoker"],dtype=int)
print(df_encoded)

   patient_id       city  smoker_No  smoker_Yes
0         601      Udupi          0           1
1         602    Manipal          1           0
2         603      Udupi          1           0
3         604  Mangalore          0           1

In [ ]:
df_new =pd.get_dummies(df_encoded,columns=["city"],drop_first=True,dtype=int)
print(df_new)
# removes first city (drops mangalore. because of alphabetical order)

   patient_id  smoker_No  smoker_Yes  city_Manipal  city_Udupi
0         601          0           1             0           1
1         602          1           0             1           0
2         603          1           0             0           1
3         604          0           1             0           0

In [30]:
df_new.columns

Index(['patient_id', 'smoker_No', 'smoker_Yes', 'city_Manipal', 'city_Udupi'], dtype='str')

In [31]:
# final df

final_df=pd.get_dummies(df,columns=["smoker","city"],dtype=int,drop_first=True)
final_df

   patient_id  smoker_Yes  city_Manipal  city_Udupi
0         601           1             0           1
1         602           0             1           0
2         603           0             0           1
3         604           1             0           0