In [26]:
import pandas as pd
import numpy as np

In [27]:
#messy data
messy_data={
    'patient_id':[201,202,203,204,205],
    'district':['Ernakulam','udupi','udupi','ernakulam','bangalore'],
    'glucose_level':[105,142,142,np.nan,98]
}

df=pd.DataFrame(messy_data)

print(df)

   patient_id   district  glucose_level
0         201  Ernakulam          105.0
1         202      udupi          142.0
2         203      udupi          142.0
3         204  ernakulam            NaN
4         205  bangalore           98.0

In [28]:
df.columns

Index(['patient_id', 'district', 'glucose_level'], dtype='str')

In [29]:
df.shape

(5, 3)

In [30]:
df.info

<bound method DataFrame.info of    patient_id   district  glucose_level
0         201  Ernakulam          105.0
1         202      udupi          142.0
2         203      udupi          142.0
3         204  ernakulam            NaN
4         205  bangalore           98.0>

In [31]:
df.isna().sum()

patient_id       0
district         0
glucose_level    1
dtype: int64

In [32]:
df['district'].unique()

<StringArray>
['Ernakulam', 'udupi', 'ernakulam', 'bangalore']
Length: 4, dtype: str

In [33]:
#remove duplicate rows
df_cleaned = df.drop_duplicates()
df_cleaned

   patient_id   district  glucose_level
0         201  Ernakulam          105.0
1         202      udupi          142.0
2         203      udupi          142.0
3         204  ernakulam            NaN
4         205  bangalore           98.0

In [34]:
df_cleaned["district"]=df_cleaned["district"].str.strip().str.title()
#it will capitalize all the first letter of values in the column
print(df_cleaned)

   patient_id   district  glucose_level
0         201  Ernakulam          105.0
1         202      Udupi          142.0
2         203      Udupi          142.0
3         204  Ernakulam            NaN
4         205  Bangalore           98.0

In [35]:
median_glucose = df_cleaned["glucose_level"].median()
median_glucose

np.float64(123.5)

In [36]:
df_cleaned["glucose_level"]=df_cleaned["glucose_level"].fillna(median_glucose)
print(df_cleaned)

   patient_id   district  glucose_level
0         201  Ernakulam          105.0
1         202      Udupi          142.0
2         203      Udupi          142.0
3         204  Ernakulam          123.5
4         205  Bangalore           98.0

In [37]:
#lets repeat this by chaning first character of district to lower case

In [38]:
df_cleaned_2=df

In [39]:
df_cleaned_2["district"]=df_cleaned["district"].str.lower()
df_cleaned_2

   patient_id   district  glucose_level
0         201  ernakulam          105.0
1         202      udupi          142.0
2         203      udupi          142.0
3         204  ernakulam            NaN
4         205  bangalore           98.0

In [40]:
#replace nan with 0 
df_cleaned_2["glucose_level"]=df_cleaned_2["glucose_level"].fillna(0)
df_cleaned_2

   patient_id   district  glucose_level
0         201  ernakulam          105.0
1         202      udupi          142.0
2         203      udupi          142.0
3         204  ernakulam            0.0
4         205  bangalore           98.0