In [1]:
import pandas as pd
import numpy as np

In [2]:
trail_data={
    'patient_id':[501,502,503],
    'treatment':["Drug_A","Placebo","Drug_A"],
    'week_1_bp':[140,150,135],
    'week_2_bp':[135,148,130],
    'week_3_bp':[120,145,128]
}

df=pd.DataFrame(trail_data)
df

   patient_id treatment  week_1_bp  week_2_bp  week_3_bp
0         501    Drug_A        140        135        120
1         502   Placebo        150        148        145
2         503    Drug_A        135        130        128

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  3 non-null      int64
 1   treatment   3 non-null      str
 2   week_1_bp   3 non-null      int64
 3   week_2_bp   3 non-null      int64
 4   week_3_bp   3 non-null      int64
dtypes: int64(4), str(1)
memory usage: 252.0 bytes

In [4]:
df.shape

(3, 5)

In [5]:
df.head(2)

   patient_id treatment  week_1_bp  week_2_bp  week_3_bp
0         501    Drug_A        140        135        120
1         502   Placebo        150        148        145

In [6]:
df.tail(2)

   patient_id treatment  week_1_bp  week_2_bp  week_3_bp
1         502   Placebo        150        148        145
2         503    Drug_A        135        130        128

In [9]:
df.describe()

       patient_id   week_1_bp   week_2_bp   week_3_bp
count         3.0    3.000000    3.000000    3.000000
mean        502.0  141.666667  137.666667  131.000000
std           1.0    7.637626    9.291573   12.767145
min         501.0  135.000000  130.000000  120.000000
25%         501.5  137.500000  132.500000  124.000000
50%         502.0  140.000000  135.000000  128.000000
75%         502.5  145.000000  141.500000  136.500000
max         503.0  150.000000  148.000000  145.000000

In [10]:
#unpivot the dataset. using melt

df_long=pd.melt(
    df,
    id_vars=["patient_id","treatment"],
    value_vars=["week_1_bp","week_2_bp","week_3_bp"],
    var_name='measurement_week',
    value_name='blood_pressure'
)

print(df_long)

   patient_id treatment measurement_week  blood_pressure
0         501    Drug_A        week_1_bp             140
1         502   Placebo        week_1_bp             150
2         503    Drug_A        week_1_bp             135
3         501    Drug_A        week_2_bp             135
4         502   Placebo        week_2_bp             148
5         503    Drug_A        week_2_bp             130
6         501    Drug_A        week_3_bp             120
7         502   Placebo        week_3_bp             145
8         503    Drug_A        week_3_bp             128

In [11]:
#clean the test

df_long["measurement_week"]=df_long["measurement_week"].str.replace("_bp",'')
df_long

   patient_id treatment measurement_week  blood_pressure
0         501    Drug_A           week_1             140
1         502   Placebo           week_1             150
2         503    Drug_A           week_1             135
3         501    Drug_A           week_2             135
4         502   Placebo           week_2             148
5         503    Drug_A           week_2             130
6         501    Drug_A           week_3             120
7         502   Placebo           week_3             145
8         503    Drug_A           week_3             128

In [12]:
#sort by patient_id/
df_long=df_long.sort_values(by=["patient_id","measurement_week"])
df_long

   patient_id treatment measurement_week  blood_pressure
0         501    Drug_A           week_1             140
3         501    Drug_A           week_2             135
6         501    Drug_A           week_3             120
1         502   Placebo           week_1             150
4         502   Placebo           week_2             148
7         502   Placebo           week_3             145
2         503    Drug_A           week_1             135
5         503    Drug_A           week_2             130
8         503    Drug_A           week_3             128