In [19]:
import pandas as pd

In [20]:
demo_data= {
    'patient_id':[101,102,103,104,105],
    'state':['kerala','karnataka','maharashtra','kerala','tamil nadu'],
    'age':[45,52,34,28,61]
}

df_demo = pd.DataFrame(demo_data)
print(df_demo)

   patient_id        state  age
0         101       kerala   45
1         102    karnataka   52
2         103  maharashtra   34
3         104       kerala   28
4         105   tamil nadu   61

In [21]:
clinical_data={
    'patient_id':[101,102,104,105],
    'hypertension_status':[1,1,0,1],
    "bmi":[26.5,29.0,22.1,31.4]
}
df_clinical=pd.DataFrame(clinical_data)
print(df_clinical)

   patient_id  hypertension_status   bmi
0         101                    1  26.5
1         102                    1  29.0
2         104                    0  22.1
3         105                    1  31.4

In [22]:
#inner merge
#merge dataset based on matching patient id

merge_inner = pd.merge(df_demo,df_clinical,on="patient_id",how="inner")

print("inner join table")
print(merge_inner)

inner join table
   patient_id       state  age  hypertension_status   bmi
0         101      kerala   45                    1  26.5
1         102   karnataka   52                    1  29.0
2         104      kerala   28                    0  22.1
3         105  tamil nadu   61                    1  31.4

In [23]:
#left merge
merge_left=pd.merge(df_demo,df_clinical,on="patient_id",how="left")
print("left join")
print(merge_left)

left join
   patient_id        state  age  hypertension_status   bmi
0         101       kerala   45                  1.0  26.5
1         102    karnataka   52                  1.0  29.0
2         103  maharashtra   34                  NaN   NaN
3         104       kerala   28                  0.0  22.1
4         105   tamil nadu   61                  1.0  31.4

In [24]:
#right join

merge_right=pd.merge(df_demo,df_clinical,on="patient_id",how="right")
print("right merge table")
print(merge_right)

right merge table
   patient_id       state  age  hypertension_status   bmi
0         101      kerala   45                    1  26.5
1         102   karnataka   52                    1  29.0
2         104      kerala   28                    0  22.1
3         105  tamil nadu   61                    1  31.4

In [27]:
# fill missing NaN with default 0
merge_left["hypertension_status"]=merge_left["hypertension_status"].fillna(0)
mean_bmi=merge_left["bmi"].mean()
merge_left["bmi"]=merge_left["bmi"].fillna(mean_bmi)
print("left merge table after filling Nan")
print(merge_left)

left merge table after filling Nan
   patient_id        state  age  hypertension_status    bmi
0         101       kerala   45                  1.0  26.50
1         102    karnataka   52                  1.0  29.00
2         103  maharashtra   34                  0.0  27.25
3         104       kerala   28                  0.0  22.10
4         105   tamil nadu   61                  1.0  31.40

In [29]:
#sort table who is more than 40 year old
merge_inner_ageabove40=merge_inner[merge_inner["age"]>40]
merge_inner_ageabove40

   patient_id       state  age  hypertension_status   bmi
0         101      kerala   45                    1  26.5
1         102   karnataka   52                    1  29.0
3         105  tamil nadu   61                    1  31.4

In [31]:
#sort table who is in kerala
merge_table_kerala=merge_inner[merge_inner["state"]=="kerala"]
merge_table_kerala

   patient_id   state  age  hypertension_status   bmi
0         101  kerala   45                    1  26.5
2         104  kerala   28                    0  22.1