In [30]:
import pandas as pd

#
case_data={
    'date':['2026-10-01','2026-10-02','2026-10-03','2026-10-04','2026-10-05'],
    'new_cases':[45,52,48,60,55]
}

df=pd.DataFrame(case_data)
df

         date  new_cases
0  2026-10-01         45
1  2026-10-02         52
2  2026-10-03         48
3  2026-10-04         60
4  2026-10-05         55

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       5 non-null      str
 1   new_cases  5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

In [32]:
df["date"]=pd.to_datetime(df["date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       5 non-null      datetime64[us]
 1   new_cases  5 non-null      int64
dtypes: datetime64[us](1), int64(1)
memory usage: 212.0 bytes

In [33]:
#ranking data


df["severity_rank"] = df["new_cases"].rank(ascending=False)

print(df)

        date  new_cases  severity_rank
0 2026-10-01         45            5.0
1 2026-10-02         52            3.0
2 2026-10-03         48            4.0
3 2026-10-04         60            1.0
4 2026-10-05         55            2.0

In [34]:
# day change

df["yesterday_cases"]= df["new_cases"].shift(1)
df

        date  new_cases  severity_rank  yesterday_cases
0 2026-10-01         45            5.0              NaN
1 2026-10-02         52            3.0             45.0
2 2026-10-03         48            4.0             52.0
3 2026-10-04         60            1.0             48.0
4 2026-10-05         55            2.0             60.0

In [36]:
# changes in case

df["daily_change"]=df["new_cases"]-df["yesterday_cases"]

df

        date  new_cases  severity_rank  yesterday_cases  daily_change
0 2026-10-01         45            5.0              NaN           NaN
1 2026-10-02         52            3.0             45.0           7.0
2 2026-10-03         48            4.0             52.0          -4.0
3 2026-10-04         60            1.0             48.0          12.0
4 2026-10-05         55            2.0             60.0          -5.0

In [37]:

df_copy_1=pd.DataFrame(case_data)
df_copy_1

         date  new_cases
0  2026-10-01         45
1  2026-10-02         52
2  2026-10-03         48
3  2026-10-04         60
4  2026-10-05         55

In [38]:
df_copy_1["date"]=pd.to_datetime(df_copy_1["date"])

In [39]:
df_copy_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       5 non-null      datetime64[us]
 1   new_cases  5 non-null      int64
dtypes: datetime64[us](1), int64(1)
memory usage: 212.0 bytes

In [41]:
df_copy_1["lowest_ranking"]=df_copy_1["new_cases"].rank(ascending=True)
df_copy_1

        date  new_cases  lowest_ranking
0 2026-10-01         45             1.0
1 2026-10-02         52             3.0
2 2026-10-03         48             2.0
3 2026-10-04         60             5.0
4 2026-10-05         55             4.0