In [1]:
import pandas as pd

clinic_data={
    'patient_id':[401,402,403,404,405],
    'age':[28,62,45,55,33],
    'fasting_sugar':[95,149,110,126,88]
}

df=pd.DataFrame(clinic_data)

df

   patient_id  age  fasting_sugar
0         401   28             95
1         402   62            149
2         403   45            110
3         404   55            126
4         405   33             88

In [2]:
df.shape

(5, 3)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patient_id     5 non-null      int64
 1   age            5 non-null      int64
 2   fasting_sugar  5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [5]:
df.describe()

       patient_id        age  fasting_sugar
count    5.000000   5.000000       5.000000
mean   403.000000  44.600000     113.600000
std      1.581139  14.328294      24.602845
min    401.000000  28.000000      88.000000
25%    402.000000  33.000000      95.000000
50%    403.000000  45.000000     110.000000
75%    404.000000  55.000000     126.000000
max    405.000000  62.000000     149.000000

In [6]:
# .apply

def diagnose_sugar(sugar_level):
    if sugar_level<100:
        return 'Normal'
    elif 100<=sugar_level<=125:
        return 'Prediabetic'
    else:
        return 'Diabetic'


#  apply the function to the fasting_sugar column
df["diagnosis"]=df["fasting_sugar"].apply(diagnose_sugar)


print(df)

   patient_id  age  fasting_sugar    diagnosis
0         401   28             95       Normal
1         402   62            149     Diabetic
2         403   45            110  Prediabetic
3         404   55            126     Diabetic
4         405   33             88       Normal

In [7]:
# using lambda

df["risk_score"]=df["age"].apply(lambda x:x*1.5)


print(df)

   patient_id  age  fasting_sugar    diagnosis  risk_score
0         401   28             95       Normal        42.0
1         402   62            149     Diabetic        93.0
2         403   45            110  Prediabetic        67.5
3         404   55            126     Diabetic        82.5
4         405   33             88       Normal        49.5

In [8]:
# age group using lambda

#df["age_group"]=df["age"].apply(lambda x:'Senior' if x>60 'Middle' elif x>30 else 'Young')
# lambda only support single expression
# need to use another if else inside

df["age_group"]=df["age"].apply(lambda x:'Senior'if x>60 else('Middle' if x>30 else 'Young'))
df

   patient_id  age  fasting_sugar    diagnosis  risk_score age_group
0         401   28             95       Normal        42.0     Young
1         402   62            149     Diabetic        93.0    Senior
2         403   45            110  Prediabetic        67.5    Middle
3         404   55            126     Diabetic        82.5    Middle
4         405   33             88       Normal        49.5    Middle