In [1]:
#
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [2]:
claim_data={
    'patient_id':[701,702,703,704,705],
    'age':[25,45,35,60,22],
    'claim_amount':[1500,45000,12000,150000,800]
}

df=pd.DataFrame(claim_data)
df

   patient_id  age  claim_amount
0         701   25          1500
1         702   45         45000
2         703   35         12000
3         704   60        150000
4         705   22           800

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    5 non-null      int64
 1   age           5 non-null      int64
 2   claim_amount  5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [5]:
df.describe()

       patient_id        age   claim_amount
count    5.000000   5.000000       5.000000
mean   703.000000  37.400000   41860.000000
std      1.581139  15.533834   63068.597574
min    701.000000  22.000000     800.000000
25%    702.000000  25.000000    1500.000000
50%    703.000000  35.000000   12000.000000
75%    704.000000  45.000000   45000.000000
max    705.000000  60.000000  150000.000000

In [6]:
# normalization
# min max scalling
columns_to_be_scaled=["age","claim_amount"]

min_max_scaler=MinMaxScaler()

#fit & transform
df_min_max=df.copy()
df_min_max

   patient_id  age  claim_amount
0         701   25          1500
1         702   45         45000
2         703   35         12000
3         704   60        150000
4         705   22           800

In [7]:
df_min_max[columns_to_be_scaled]=min_max_scaler.fit_transform(df[columns_to_be_scaled])
df_min_max

   patient_id       age  claim_amount
0         701  0.078947      0.004692
1         702  0.605263      0.296247
2         703  0.342105      0.075067
3         704  1.000000      1.000000
4         705  0.000000      0.000000

In [8]:
# using standard scaling

std_scaler=StandardScaler()
df_standard=df.copy()

df_standard[columns_to_be_scaled]=std_scaler.fit_transform(df_standard[columns_to_be_scaled])
df_standard

   patient_id       age  claim_amount
0         701 -0.892479     -0.715473
1         702  0.547003      0.055664
2         703 -0.172738     -0.529336
3         704  1.626615      1.917027
4         705 -1.108401     -0.727882

In [11]:
df_copy=df.copy()
std_scaler=StandardScaler()
df_copy["claim_amount"]=std_scaler.fit_transform(df_copy[["claim_amount"]])
df_copy

   patient_id  age  claim_amount
0         701   25     -0.715473
1         702   45      0.055664
2         703   35     -0.529336
3         704   60      1.917027
4         705   22     -0.727882