# Dates and times

In [47]:
import pandas as pd
import numpy as np

In [48]:
admission_data={
    'patient_id':[301,302,303,304,305],
    'admission_date':['2025-11-15','2026-01-05','2026-03-22','2025-12-10','2026-06-18'],
    'diagnosis_code':['A1','B2','A1','C3','B2']
}
df=pd.DataFrame(admission_data)
print("--- data ----")
df

--- data ----

   patient_id admission_date diagnosis_code
0         301     2025-11-15             A1
1         302     2026-01-05             B2
2         303     2026-03-22             A1
3         304     2025-12-10             C3
4         305     2026-06-18             B2

In [49]:
#data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      5 non-null      int64
 1   admission_date  5 non-null      str
 2   diagnosis_code  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [50]:
#convert date to date type

df["admission_date"]=pd.to_datetime(df["admission_date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      5 non-null      int64
 1   admission_date  5 non-null      datetime64[us]
 2   diagnosis_code  5 non-null      str
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 252.0 bytes

In [51]:
#to extract month and year from the date column

df["admit_year"]=df["admission_date"].dt.year

df["admit_month"]=df["admission_date"].dt.month

print("updated data frame with date month and year separate columns")
print(df)

updated data frame with date month and year separate columns
   patient_id admission_date diagnosis_code  admit_year  admit_month
0         301     2025-11-15             A1        2025           11
1         302     2026-01-05             B2        2026            1
2         303     2026-03-22             A1        2026            3
3         304     2025-12-10             C3        2025           12
4         305     2026-06-18             B2        2026            6

In [52]:
#df["admit_day"]=df["admission_date"].dt.weekday

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      5 non-null      int64
 1   admission_date  5 non-null      datetime64[us]
 2   diagnosis_code  5 non-null      str
 3   admit_year      5 non-null      int32
 4   admit_month     5 non-null      int32
dtypes: datetime64[us](1), int32(2), int64(1), str(1)
memory usage: 292.0 bytes

In [54]:
#filtering patient admitted based on date

admission_2026=df[df["admission_date"]>="2026-01-01"]
admission_2026

   patient_id admission_date diagnosis_code  admit_year  admit_month
1         302     2026-01-05             B2        2026            1
2         303     2026-03-22             A1        2026            3
4         305     2026-06-18             B2        2026            6

In [55]:
#between march 01 - 31

admission_march = df[(df["admission_date"]>="2026-03-01") & (df["admission_date"]<="2026-03-31")]
admission_march

   patient_id admission_date diagnosis_code  admit_year  admit_month
2         303     2026-03-22             A1        2026            3

In [56]:
#current date
import datetime
today = datetime.date.today()
today

datetime.date(2026, 9, 28)

In [57]:
# if
day_1 = datetime.date(2026,3,19)
number_of_days=(today-day_1).days
number_of_days

193

In [58]:
# for dataframe date

date_today=pd.Timestamp.today().normalize() #normalize to remove time 
df["admission_days_till_now"] = (date_today - df["admission_date"])
df

,patient_id,admission_date,diagnosis_code,admit_year,admit_month,admission_days_till_now
0,301,2025-11-15,A1,2025,11,317 days
1,302,2026-01-05,B2,2026,1,266 days
2,303,2026-03-22,A1,2026,3,190 days
3,304,2025-12-10,C3,2025,12,292 days
4,305,2026-06-18,B2,2026,6,102 days