In [6]:
import pandas as pd

In [7]:
demographics=pd.DataFrame(
    {
        'patient_id':[901,902,903,904],
        'name':['Alice',"Rose","Oliver","Justin"]
    }
)

labs=pd.DataFrame({
    'patient_id':[901,902,903,905],
    "cholestrol":[180,220,195,240]
})

print(demographics)

   patient_id    name
0         901   Alice
1         902    Rose
2         903  Oliver
3         904  Justin

In [8]:
print(labs)

   patient_id  cholestrol
0         901         180
1         902         220
2         903         195
3         905         240

In [9]:
#inner merge

inner_df=pd.merge(demographics,labs,on="patient_id",how="inner")
print(inner_df)

   patient_id    name  cholestrol
0         901   Alice         180
1         902    Rose         220
2         903  Oliver         195

In [10]:
#left merge

left_df=pd.merge(demographics,labs,on="patient_id",how="left")
print(left_df)

   patient_id    name  cholestrol
0         901   Alice       180.0
1         902    Rose       220.0
2         903  Oliver       195.0
3         904  Justin         NaN

In [11]:
#to fill the missing value
left_df["cholestrol"]=left_df["cholestrol"].fillna("not entered")
left_df

   patient_id    name   cholestrol
0         901   Alice        180.0
1         902    Rose        220.0
2         903  Oliver        195.0
3         904  Justin  not entered

In [12]:
#riht join
right_df=pd.merge(demographics,labs,on="patient_id",how="right")
right_df

   patient_id    name  cholestrol
0         901   Alice         180
1         902    Rose         220
2         903  Oliver         195
3         905     NaN         240

In [13]:
#outer join
outer_join=pd.merge(demographics,labs,on="patient_id",how="outer")
print("outer join","\n",outer_join)

outer join
    patient_id    name  cholestrol
0         901   Alice       180.0
1         902    Rose       220.0
2         903  Oliver       195.0
3         904  Justin         NaN
4         905     NaN       240.0